/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasAdmin;

import java.awt.Point;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonUI;
import BD.Conexion;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Lenovo
 */
public class AgregarP extends javax.swing.JFrame {

    private Point point;
    static String NombreArchivo = "NoImageSelected.png";

    /**
     * Creates new form AgregarP
     */
    public AgregarP() {
        initComponents();
        JButton[] btns = {agregar, si, guardar, agregar1};
        for (JButton btn : btns) {
            btn.setBackground(new Color(67, 60, 84));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(153, 153, 255));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(67, 60, 84));
                }
            });
            guardar.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        type = new javax.swing.JComboBox<>();
        agregar = new javax.swing.JButton();
        si = new javax.swing.JButton();
        font = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nombre1 = new javax.swing.JTextField();
        Lup = new javax.swing.JPanel();
        Lup1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Unidades = new javax.swing.JTextField();
        agregar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(241, 226, 205));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(29, 26, 37));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 20, 530));

        jPanel4.setBackground(new java.awt.Color(29, 26, 37));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 10, 530));

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 26, 37));
        jLabel1.setText("Agregar Productos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 400, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(29, 26, 37));
        jLabel2.setText("Unidades:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 110, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(29, 26, 37));
        jLabel3.setText("Nombre del producto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 210, -1));

        precio.setBackground(new java.awt.Color(67, 60, 84));
        precio.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        precio.setForeground(new java.awt.Color(233, 212, 181));
        precio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 26, 37)));
        precio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                precioMouseClicked(evt);
            }
        });
        precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioActionPerformed(evt);
            }
        });
        precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioKeyTyped(evt);
            }
        });
        jPanel1.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 190, -1));

        type.setBackground(new java.awt.Color(67, 60, 84));
        type.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        type.setForeground(new java.awt.Color(29, 26, 37));
        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mujer", "Hombre", "Nino/a", "Accesorios" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 190, -1));

        agregar.setBackground(new java.awt.Color(67, 60, 84));
        agregar.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        agregar.setForeground(new java.awt.Color(233, 212, 181));
        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 180, 30));

        si.setBackground(new java.awt.Color(67, 60, 84));
        si.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        si.setForeground(new java.awt.Color(233, 212, 181));
        si.setText("Seleccionar y guardar imagen");
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });
        jPanel1.add(si, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 300, 30));

        font.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 26, 37), 3));
        jPanel1.add(font, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 490, 290));

        guardar.setBackground(new java.awt.Color(67, 60, 84));
        guardar.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        guardar.setForeground(new java.awt.Color(233, 212, 181));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 510, 110, 30));

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(29, 26, 37));
        jLabel4.setText("Tipo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 60, -1));

        nombre1.setBackground(new java.awt.Color(67, 60, 84));
        nombre1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        nombre1.setForeground(new java.awt.Color(233, 212, 181));
        nombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 26, 37)));
        nombre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombre1MouseClicked(evt);
            }
        });
        nombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombre1ActionPerformed(evt);
            }
        });
        nombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre1KeyTyped(evt);
            }
        });
        jPanel1.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 190, -1));

        Lup.setBackground(new java.awt.Color(29, 26, 37));
        Lup.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout LupLayout = new javax.swing.GroupLayout(Lup);
        Lup.setLayout(LupLayout);
        LupLayout.setHorizontalGroup(
            LupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LupLayout.setVerticalGroup(
            LupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(Lup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1030, -1));

        Lup1.setBackground(new java.awt.Color(29, 26, 37));
        Lup1.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout Lup1Layout = new javax.swing.GroupLayout(Lup1);
        Lup1.setLayout(Lup1Layout);
        Lup1Layout.setHorizontalGroup(
            Lup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Lup1Layout.setVerticalGroup(
            Lup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(Lup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(29, 26, 37));
        jLabel5.setText("Precio:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 70, -1));

        Unidades.setBackground(new java.awt.Color(67, 60, 84));
        Unidades.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Unidades.setForeground(new java.awt.Color(233, 212, 181));
        Unidades.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 26, 37)));
        Unidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UnidadesMouseClicked(evt);
            }
        });
        Unidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnidadesActionPerformed(evt);
            }
        });
        Unidades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UnidadesKeyTyped(evt);
            }
        });
        jPanel1.add(Unidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 190, -1));

        agregar1.setBackground(new java.awt.Color(67, 60, 84));
        agregar1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        agregar1.setForeground(new java.awt.Color(233, 212, 181));
        agregar1.setText("Regresar:");
        agregar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 26, 37), 2));
        agregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar1ActionPerformed(evt);
            }
        });
        jPanel1.add(agregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 170, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1011, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void precioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precioMouseClicked
        // TODO add your handling code here:
        precio.setText("");
    }//GEN-LAST:event_precioMouseClicked

    private void precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        String tipo = "";
        tipo = type.getSelectedItem().toString();

        String sentenciaSQL = "INSERT INTO Productos  (Nombre, etiqueta, tipo, Precio,Nimagen, Stock) VALUES ('" + nombre1.getText() + "',null,'" + tipo + "','" + precio.getText() + "','" + NombreArchivo + "','" + Unidades.getText() + "')";
        Conexion c = new Conexion();
        c.añadir(sentenciaSQL);

    }//GEN-LAST:event_agregarActionPerformed

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
        // TODO add your handling code here:
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AgregarP.class.getName()).log(Level.SEVERE, null, ex);
        }

        JFileChooser fileChooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG, PNG, JPEG Images", "jpg", "png", "jpeg");
        fileChooser.setFileFilter(filter);

        int selection = fileChooser.showOpenDialog(null);

        if (selection == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String selectedFileName = selectedFile.getName();

            if (selectedFileName.endsWith(".jpg") || selectedFileName.endsWith(".png") || selectedFileName.endsWith(".jpeg")) {
                File destinationFile = new File("D:/prueba/" + selectedFileName);

                try {
                    BufferedImage image = ImageIO.read(selectedFile);
                    ImageIO.write(image, "png", destinationFile);
                    System.out.println("Imagen guardada exitosamente en: " + destinationFile.getAbsolutePath());

                    // Para mostrar la imagen en un JLabel (aquí asumiendo que 'font' es un JLabel)
                    ImageIcon icon = new ImageIcon(destinationFile.getAbsolutePath());
                    Image scaledImage = icon.getImage().getScaledInstance(font.getWidth(), font.getHeight(), Image.SCALE_SMOOTH);
                    ImageIcon scaledIcon = new ImageIcon(scaledImage);
                    font.setIcon(scaledIcon);

                    JOptionPane.showMessageDialog(null, "Imagen guardada exitosamente en: " + destinationFile.getAbsolutePath(), "Imagen", JOptionPane.INFORMATION_MESSAGE);
                    JOptionPane.showMessageDialog(null, "El nombre de la imagen es: " + selectedFileName, "Nombre", JOptionPane.INFORMATION_MESSAGE);
                    System.out.println("El nombre es: " + selectedFileName);
                    NombreArchivo = selectedFileName;
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Formato no válido. Selecciona una imagen en formato JPG o PNG.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            System.out.println("El usuario canceló la operación de abrir.");
        }
    }//GEN-LAST:event_siActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(AgregarP.class.getName()).log(Level.SEVERE, null, ex);
        }

        JFileChooser fileChooser = new JFileChooser();

        // Mostrar el cuadro de diálogo para seleccionar un archivo de imagen
        int seleccion = fileChooser.showOpenDialog(null);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            // El usuario seleccionó un archivo de imagen y eligió la opción "Abrir"
            File archivoSeleccionado = fileChooser.getSelectedFile();
            String nombreArchivoSeleccionado = archivoSeleccionado.getName(); // Obtener el nombre del archivo

            // Verificar que el archivo seleccionado sea una imagen válida
            if (nombreArchivoSeleccionado.endsWith(".jpg") || nombreArchivoSeleccionado.endsWith(".png") || nombreArchivoSeleccionado.endsWith(".jpeg")) {
                // Definir la ubicación de destino
                File archivoDestino = new File("D:/prueba/" + nombreArchivoSeleccionado);

                // Intentar copiar el archivo seleccionado a la ubicación de destino
                try {
                    BufferedImage imagen = ImageIO.read(archivoSeleccionado);
                    // Guardar la imagen en formato PNG en la ubicación de destino
                    ImageIO.write(imagen, "png", archivoDestino);
                    System.out.println("Imagen guardada exitosamente en: " + archivoDestino.getAbsolutePath());
                    JOptionPane.showMessageDialog(null, "Imagen guardada exitosamente en: " + archivoDestino.getAbsolutePath(), "Imagen", JOptionPane.INFORMATION_MESSAGE);
                    JOptionPane.showMessageDialog(null, "El nombre de la imagen es: " + nombreArchivoSeleccionado, "Nombre", JOptionPane.INFORMATION_MESSAGE);
                    System.out.println("El nombre es: " + nombreArchivoSeleccionado);
                    NombreArchivo = nombreArchivoSeleccionado;
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Formato no válido. Selecciona una imagen en formato JPG o PNG.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            System.out.println("El usuario canceló la operación de abrir.");
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void nombre1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombre1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre1MouseClicked

    private void nombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombre1ActionPerformed

    private void UnidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UnidadesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UnidadesMouseClicked

    private void UnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnidadesActionPerformed

    private void agregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_agregar1ActionPerformed

    private void nombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre1KeyTyped
        // TODO add your handling code here:
        if (!Character.isLetter(evt.getKeyChar()) && evt.getKeyChar() != ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_nombre1KeyTyped

    private void precioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) || precio.getText().length() >= 11) {
            evt.consume();
        }
    }//GEN-LAST:event_precioKeyTyped

    private void UnidadesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UnidadesKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()) || Unidades.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_UnidadesKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Lup;
    private javax.swing.JPanel Lup1;
    private javax.swing.JTextField Unidades;
    private javax.swing.JButton agregar;
    private javax.swing.JButton agregar1;
    private javax.swing.JLabel font;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField precio;
    private javax.swing.JButton si;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
