package vistasUser;

import BD.Conexion;
import BD.Configuracion;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author PC
 */
public class Hombre extends javax.swing.JFrame {

    private Point point;
    Conexion co = new Conexion();
    private Configuracion configuracion = Configuracion.getInstance();
    boolean idiomaActual;

    public Hombre() {
        idiomaActual = configuracion.isIdioma();
        setUndecorated(true);
        initComponents();
        JButton[] btns = {Accesorios, Carrito, Mujer, Instagram, Instagram1, Niño, Twitter, Home, addC1, addC2, addC3, Sig, back, Filtrar, NoFil};
        for (JButton btn : btns) {
            btn.setBackground(new Color(67, 60, 84));//color del boton original
            btn.setForeground(new Color(233, 212, 181));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(233, 212, 181));//color que tomara cuando pase el jerry por encima
                    btn.setForeground(new Color(67, 60, 84));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(67, 60, 84));//color del boton original que recupera
                    btn.setForeground(new Color(233, 212, 181));
                }
            });
        }
        JButton[] btns1 = {Mcerrar};
        for (JButton btn1 : btns1) {
            btn1.setBackground(new Color(241, 226, 205));
            btn1.setUI(new BasicButtonUI());
            btn1.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {

                }

                @Override
                public void mousePressed(MouseEvent e) {

                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn1.setBackground(new Color(193, 28, 28));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn1.setBackground(new Color(241, 226, 205));
                }
            });
        }
        JButton[] btns2 = {Mminimizar};
        for (JButton btn2 : btns2) {
            btn2.setBackground(new Color(241, 226, 205));
            btn2.setUI(new BasicButtonUI());
            btn2.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn2.setBackground(new Color(233, 212, 181));
                }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn2.setBackground(new Color(241, 226, 205));
                }
            });
        }
        setLocationRelativeTo(null);
        ConsultaIDs();
        Sig.doClick();
        tra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CMA = new javax.swing.JPanel();
        Mcerrar = new javax.swing.JButton();
        Mminimizar = new javax.swing.JButton();
        Fondo = new javax.swing.JPanel();
        Lup = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        LDown = new javax.swing.JPanel();
        Menu1 = new javax.swing.JPanel();
        Carrito = new javax.swing.JButton();
        Mujer = new javax.swing.JButton();
        Hombre = new javax.swing.JButton();
        Niño = new javax.swing.JButton();
        Accesorios = new javax.swing.JButton();
        Bienvenido2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Bienvenido3 = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        back = new javax.swing.JButton();
        Info1 = new javax.swing.JLabel();
        addC1 = new javax.swing.JButton();
        addC2 = new javax.swing.JButton();
        Info2 = new javax.swing.JLabel();
        addC3 = new javax.swing.JButton();
        Info3 = new javax.swing.JLabel();
        Image3 = new javax.swing.JLabel();
        Sig = new javax.swing.JButton();
        Image2 = new javax.swing.JLabel();
        Image1 = new javax.swing.JLabel();
        filtro = new javax.swing.JComboBox<>();
        Filtrar = new javax.swing.JButton();
        NoFil = new javax.swing.JButton();
        IconoBuscar = new javax.swing.JLabel();
        redes = new javax.swing.JTextField();
        Twitter = new javax.swing.JButton();
        Instagram = new javax.swing.JButton();
        Contacto1 = new javax.swing.JTextField();
        Instagram1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CMA.setBackground(new java.awt.Color(241, 226, 205));
        CMA.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                CMAMouseDragged(evt);
            }
        });
        CMA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CMAMousePressed(evt);
            }
        });

        Mcerrar.setBackground(new java.awt.Color(241, 226, 205));
        Mcerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cancel (1).png"))); // NOI18N
        Mcerrar.setBorder(null);
        Mcerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                McerrarActionPerformed(evt);
            }
        });

        Mminimizar.setBackground(new java.awt.Color(241, 226, 205));
        Mminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/minus (1).png"))); // NOI18N
        Mminimizar.setBorder(null);
        Mminimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MminimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CMALayout = new javax.swing.GroupLayout(CMA);
        CMA.setLayout(CMALayout);
        CMALayout.setHorizontalGroup(
            CMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CMALayout.createSequentialGroup()
                .addContainerGap(1112, Short.MAX_VALUE)
                .addComponent(Mminimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Mcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CMALayout.setVerticalGroup(
            CMALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mcerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(Mminimizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(CMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 30));

        Fondo.setBackground(new java.awt.Color(241, 226, 205));
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lup.setBackground(new java.awt.Color(29, 26, 37));

        javax.swing.GroupLayout LupLayout = new javax.swing.GroupLayout(Lup);
        Lup.setLayout(LupLayout);
        LupLayout.setHorizontalGroup(
            LupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LupLayout.setVerticalGroup(
            LupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        Fondo.add(Lup, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 1, 940, -1));

        Nombre.setBackground(new java.awt.Color(0, 153, 153));
        Nombre.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        Nombre.setForeground(new java.awt.Color(29, 26, 37));
        Nombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/man_1.png"))); // NOI18N
        Nombre.setText("SECCION Masculina");
        Fondo.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 19, -1, -1));

        LDown.setBackground(new java.awt.Color(29, 26, 37));

        javax.swing.GroupLayout LDownLayout = new javax.swing.GroupLayout(LDown);
        LDown.setLayout(LDownLayout);
        LDownLayout.setHorizontalGroup(
            LDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LDownLayout.setVerticalGroup(
            LDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        Fondo.add(LDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 89, 940, -1));

        Menu1.setBackground(new java.awt.Color(29, 26, 37));
        Menu1.setForeground(new java.awt.Color(204, 255, 255));

        Carrito.setBackground(new java.awt.Color(67, 60, 84));
        Carrito.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Carrito.setForeground(new java.awt.Color(233, 212, 181));
        Carrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/shopping-cart.png"))); // NOI18N
        Carrito.setText("Carrito");
        Carrito.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 212, 181)));
        Carrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarritoActionPerformed(evt);
            }
        });

        Mujer.setBackground(new java.awt.Color(67, 60, 84));
        Mujer.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Mujer.setForeground(new java.awt.Color(233, 212, 181));
        Mujer.setText("Mujer");
        Mujer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 212, 181)));
        Mujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MujerActionPerformed(evt);
            }
        });

        Hombre.setBackground(new java.awt.Color(153, 153, 255));
        Hombre.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Hombre.setForeground(new java.awt.Color(233, 212, 181));
        Hombre.setText("Hombre");
        Hombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 212, 181), 3));
        Hombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HombreActionPerformed(evt);
            }
        });

        Niño.setBackground(new java.awt.Color(67, 60, 84));
        Niño.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Niño.setForeground(new java.awt.Color(233, 212, 181));
        Niño.setText("Niño/a");
        Niño.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 212, 181)));
        Niño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NiñoActionPerformed(evt);
            }
        });

        Accesorios.setBackground(new java.awt.Color(67, 60, 84));
        Accesorios.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Accesorios.setForeground(new java.awt.Color(233, 212, 181));
        Accesorios.setText("Accesorios");
        Accesorios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 212, 181)));
        Accesorios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Accesorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccesoriosActionPerformed(evt);
            }
        });

        Bienvenido2.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        Bienvenido2.setForeground(new java.awt.Color(233, 212, 181));
        Bienvenido2.setText("Acerca de:");

        jPanel2.setBackground(new java.awt.Color(241, 226, 205));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        Bienvenido3.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        Bienvenido3.setForeground(new java.awt.Color(233, 212, 181));
        Bienvenido3.setText("Categorias:");

        Home.setBackground(new java.awt.Color(67, 60, 84));
        Home.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        Home.setForeground(new java.awt.Color(233, 212, 181));
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home.png"))); // NOI18N
        Home.setText("Inicio");
        Home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(233, 212, 181)));
        Home.setBorderPainted(false);
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Menu1Layout = new javax.swing.GroupLayout(Menu1);
        Menu1.setLayout(Menu1Layout);
        Menu1Layout.setHorizontalGroup(
            Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Menu1Layout.createSequentialGroup()
                .addGroup(Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Menu1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bienvenido2)
                            .addComponent(Carrito, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Menu1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Accesorios, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(Niño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Hombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mujer, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bienvenido3))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        Menu1Layout.setVerticalGroup(
            Menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Menu1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Home, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Bienvenido3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Mujer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Hombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Niño, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Accesorios, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(Bienvenido2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Carrito, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        Fondo.add(Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, -1));

        back.setBackground(new java.awt.Color(67, 60, 84));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/left-arrow.png"))); // NOI18N
        back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 60, 84), 2));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        Fondo.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 50, 60));

        Info1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Info1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 63, 65), 2));
        Fondo.add(Info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 210, 100));

        addC1.setBackground(new java.awt.Color(67, 60, 84));
        addC1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        addC1.setForeground(new java.awt.Color(233, 212, 181));
        addC1.setText("Agregar al carrito");
        addC1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 60, 84), 2));
        addC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addC1ActionPerformed(evt);
            }
        });
        Fondo.add(addC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 570, 170, -1));

        addC2.setBackground(new java.awt.Color(67, 60, 84));
        addC2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        addC2.setForeground(new java.awt.Color(233, 212, 181));
        addC2.setText("Agregar al carrito");
        addC2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 60, 84), 2));
        addC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addC2ActionPerformed(evt);
            }
        });
        Fondo.add(addC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 160, -1));

        Info2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Info2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 63, 65), 2));
        Fondo.add(Info2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 210, 100));

        addC3.setBackground(new java.awt.Color(67, 60, 84));
        addC3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        addC3.setForeground(new java.awt.Color(233, 212, 181));
        addC3.setText("Agregar al carrito");
        addC3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 60, 84), 2));
        addC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addC3ActionPerformed(evt);
            }
        });
        Fondo.add(addC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, 170, -1));

        Info3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Info3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 63, 65), 2));
        Fondo.add(Info3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 450, 210, 100));

        Image3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 26, 37), 2));
        Fondo.add(Image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, 210, 260));

        Sig.setBackground(new java.awt.Color(67, 60, 84));
        Sig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/raw.png"))); // NOI18N
        Sig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 60, 84), 2));
        Sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SigActionPerformed(evt);
            }
        });
        Fondo.add(Sig, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 410, 50, 60));

        Image2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 26, 37), 2));
        Fondo.add(Image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 210, 260));

        Image1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 26, 37), 2));
        Fondo.add(Image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 210, 260));

        filtro.setBackground(new java.awt.Color(67, 60, 84));
        filtro.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        filtro.setForeground(new java.awt.Color(233, 212, 181));
        filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Camisa", "Jean", "Deportivo", "Sueter", "Abrigo", "Elegante" }));
        filtro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(67, 60, 84), 3));
        filtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtroActionPerformed(evt);
            }
        });
        Fondo.add(filtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 150, 40));

        Filtrar.setBackground(new java.awt.Color(67, 60, 84));
        Filtrar.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Filtrar.setForeground(new java.awt.Color(233, 212, 181));
        Filtrar.setText("Filtrar");
        Filtrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 26, 37), 2));
        Filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrarActionPerformed(evt);
            }
        });
        Fondo.add(Filtrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 70, 40));

        NoFil.setBackground(new java.awt.Color(67, 60, 84));
        NoFil.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        NoFil.setForeground(new java.awt.Color(233, 212, 181));
        NoFil.setText("Quitar Filtros");
        NoFil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 26, 37), 2));
        NoFil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoFilActionPerformed(evt);
            }
        });
        Fondo.add(NoFil, new org.netbeans.lib.awtextra.AbsoluteConstraints(1042, 120, 130, 40));

        IconoBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IconoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/magnifying-glass.png"))); // NOI18N
        Fondo.add(IconoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 40, 40));

        redes.setEditable(false);
        redes.setBackground(new java.awt.Color(67, 60, 84));
        redes.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        redes.setForeground(new java.awt.Color(233, 212, 181));
        redes.setText(" Siguenos en nuestras redes");
        redes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 26, 37), 2));
        redes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redesActionPerformed(evt);
            }
        });
        Fondo.add(redes, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 650, 260, 36));

        Twitter.setBackground(new java.awt.Color(67, 60, 84));
        Twitter.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Twitter.setForeground(new java.awt.Color(233, 212, 181));
        Twitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/twitter.png"))); // NOI18N
        Twitter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 26, 37), 2));
        Twitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwitterActionPerformed(evt);
            }
        });
        Fondo.add(Twitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 650, -1, -1));

        Instagram.setBackground(new java.awt.Color(67, 60, 84));
        Instagram.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Instagram.setForeground(new java.awt.Color(0, 153, 153));
        Instagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/instagram.png"))); // NOI18N
        Instagram.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 26, 37), 2));
        Instagram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstagramActionPerformed(evt);
            }
        });
        Fondo.add(Instagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 650, -1, -1));

        Contacto1.setEditable(false);
        Contacto1.setBackground(new java.awt.Color(67, 60, 84));
        Contacto1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Contacto1.setForeground(new java.awt.Color(233, 212, 181));
        Contacto1.setText("Contactanos");
        Contacto1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 26, 37), 2));
        Fondo.add(Contacto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 650, 120, 36));

        Instagram1.setBackground(new java.awt.Color(67, 60, 84));
        Instagram1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        Instagram1.setForeground(new java.awt.Color(0, 153, 153));
        Instagram1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/whatsapp.png"))); // NOI18N
        Instagram1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 26, 37), 2));
        Instagram1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Instagram1ActionPerformed(evt);
            }
        });
        Fondo.add(Instagram1, new org.netbeans.lib.awtextra.AbsoluteConstraints(886, 650, -1, -1));

        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1190, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CMAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMAMousePressed
        point = evt.getPoint();
        getComponentAt(point);
    }//GEN-LAST:event_CMAMousePressed

    private void CMAMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CMAMouseDragged
        int CurrentX = this.getLocation().x;
        int CurrentY = this.getLocation().y;

        int MoveX = (CurrentX + evt.getX()) - (CurrentX + point.x);
        int MoveY = (CurrentY + evt.getY()) - (CurrentY + point.y);

        int x = CurrentX + MoveX;
        int y = CurrentY + MoveY;

        this.setLocation(x, y);
    }//GEN-LAST:event_CMAMouseDragged
    private static void openWebPage(String url) {
        try {
            Desktop.getDesktop().browse(new URI(url));
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }
    private void McerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_McerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_McerrarActionPerformed

    private void MminimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MminimizarActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_MminimizarActionPerformed

    private void CarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarritoActionPerformed
        Carrito form = new Carrito();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CarritoActionPerformed

    private void MujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MujerActionPerformed
        Mujer form = new Mujer();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MujerActionPerformed

    private void HombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HombreActionPerformed
        Hombre form = new Hombre();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HombreActionPerformed

    private void NiñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NiñoActionPerformed
        Niño form = new Niño();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_NiñoActionPerformed

    private void AccesoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccesoriosActionPerformed
        Accesorios form = new Accesorios();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AccesoriosActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        Principal form = new Principal();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed
    private int posicionActualSig = 0;
    private int posicionActualBack = 0;
    private List<Integer> idArray = new ArrayList<>();

    public void ConsultaIDs() {
        try {
            // Recupera la lista de etiquetas de productos con tipo "Mujer"
            String consultaIDs = "SELECT etiqueta FROM Productos WHERE tipo = 'Hombre'";
            ResultSet resultadoIDs = co.consultar(consultaIDs);
            while (resultadoIDs.next()) {
                int etiqueta = resultadoIDs.getInt("etiqueta");
                idArray.add(etiqueta);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        if (posicionActualBack > 0) {
            posicionActualBack--;
        } else {
            posicionActualBack = idArray.size() - 1;
        }

        int posicion = posicionActualBack % idArray.size();

        LabelM1(Image1, idArray.get(posicion), Info1);
        LabelM2(Image2, idArray.get((posicion + 1) % idArray.size()), Info2);
        LabelM3(Image3, idArray.get((posicion + 2) % idArray.size()), Info3);
    }//GEN-LAST:event_backActionPerformed

    private void addC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addC1ActionPerformed
        String input = JOptionPane.showInputDialog("Por favor, ingrese cuantas unidades desea llevar");
        int unidades = 1;
        try {
            unidades = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Numero de unidades invalido, se agrego una sola unidad");
        }
        Conexion helado = new Conexion();
        helado.carrito(nombre, etiqueta, tipo, precio, unidades, Nimagen);
    }//GEN-LAST:event_addC1ActionPerformed

    private void addC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addC2ActionPerformed
        String input = JOptionPane.showInputDialog("Por favor, ingrese cuantas unidades desea llevar");
        int unidades = 1;
        try {
            unidades = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Numero de unidades invalido, se agrego una sola unidad");
        }
        Conexion helado = new Conexion();
        helado.carrito(nombre2, etiqueta2, tipo2, precio2, unidades, Nimagen2);
    }//GEN-LAST:event_addC2ActionPerformed

    private void addC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addC3ActionPerformed
        String input = JOptionPane.showInputDialog("Por favor, ingrese cuantas unidades desea llevar");
        int unidades = 1;
        try {
            unidades = Integer.parseInt(input);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Numero de unidades invalido, se agrego una sola unidad");
        }
        Conexion helado = new Conexion();
        helado.carrito(nombre3, etiqueta3, tipo3, precio3, unidades, Nimagen3);
    }//GEN-LAST:event_addC3ActionPerformed

    private void SigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SigActionPerformed
        // TODO add your handling code here:

        if (idArray.isEmpty()) {
            System.out.println("No hay elementos en idArray");
            return;
        }
        int posicion = posicionActualSig % idArray.size();
        int tamArray = idArray.size();
        if (tamArray == 1) {
            LabelM1(Image1, idArray.get(posicion), Info1);
            Image2.setVisible(false);
            Info2.setVisible(false);
            addC2.setVisible(false);
            Image3.setVisible(false);
            Info3.setVisible(false);
            addC3.setVisible(false);
            back.setVisible(false);
            Sig.setVisible(false);
        } else if (tamArray == 2) {
            LabelM1(Image1, idArray.get(posicion), Info1);
            LabelM2(Image2, idArray.get((posicion + 1) % idArray.size()), Info2);
            Image2.setVisible(true);
            Info2.setVisible(true);
            addC2.setVisible(true);
            Image3.setVisible(false);
            Info3.setVisible(false);
            addC3.setVisible(false);
            back.setVisible(false);
            Sig.setVisible(false);
        } else if (tamArray == 3) {
            LabelM1(Image1, idArray.get(posicion), Info1);
            LabelM2(Image2, idArray.get((posicion + 1) % idArray.size()), Info2);
            LabelM3(Image3, idArray.get((posicion + 2) % idArray.size()), Info3);
            Image2.setVisible(true);
            Info2.setVisible(true);
            addC2.setVisible(true);
            Image3.setVisible(true);
            Info3.setVisible(true);
            addC3.setVisible(true);
            back.setVisible(false);
            Sig.setVisible(false);
        }else if (tamArray >= 3) {
            LabelM1(Image1, idArray.get(posicion), Info1);
            LabelM2(Image2, idArray.get((posicion + 1) % idArray.size()), Info2);
            LabelM3(Image3, idArray.get((posicion + 2) % idArray.size()), Info3);
            Image2.setVisible(true);
            Info2.setVisible(true);
            addC2.setVisible(true);
            Image3.setVisible(true);
            Info3.setVisible(true);
            addC3.setVisible(true);
            back.setVisible(true);
            Sig.setVisible(true);
        }
        
        // Incrementa la posición actual para el botón "Sig" para la próxima vez
        posicionActualSig++;
    }//GEN-LAST:event_SigActionPerformed

    private void FiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrarActionPerformed
        String filtroa = "";
        filtroa = filtro.getSelectedItem().toString();        // TODO add your handling code here:
        System.out.println(filtroa);
        idArray.removeAll(idArray);

        try {
            // Recupera la lista de etiquetas de productos con tipo "Mujer"
            String consultaIDs = "SELECT etiqueta FROM Productos WHERE tipo = 'Hombre' AND Nombre LIKE '%" + filtroa + "%'";
            ResultSet resultadoIDs = co.consultar(consultaIDs);
            while (resultadoIDs.next()) {
                int etiqueta = resultadoIDs.getInt("etiqueta");
                idArray.add(etiqueta);
                Sig.doClick();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_FiltrarActionPerformed

    private void NoFilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoFilActionPerformed
        // TODO add your handling code here:
        ConsultaIDs();
        Sig.doClick();
    }//GEN-LAST:event_NoFilActionPerformed

    private void filtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filtroActionPerformed

    private void redesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redesActionPerformed

    private void InstagramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstagramActionPerformed
        // TODO add your handling code here:
        openWebPage("https://instagram.com/lelegance_darcy05?igshid=OGQ5ZDc2ODk2ZA==");
    }//GEN-LAST:event_InstagramActionPerformed

    private void TwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwitterActionPerformed
        // TODO add your handling code here:
        openWebPage("https://twitter.com/URBANOSTORE05?t=nGlyttEKwB2M877W8TntNA&s=09");
    }//GEN-LAST:event_TwitterActionPerformed

    private void Instagram1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Instagram1ActionPerformed
        // TODO add your handling code here:
        openWebPage("https://wa.me/573022311918");
    }//GEN-LAST:event_Instagram1ActionPerformed
    String nombre;
    int etiqueta;
    String tipo;
    float precio;
    String Nimagen;
    int stock1;
    String textoProducto1;

    public void LabelM1(JLabel promo, int ID, JLabel Text) {
        String SentenciaSQL = "Select Nombre, etiqueta, tipo, precio, Nimagen, Stock FROM Productos WHERE etiqueta = " + ID;
        try {

            ResultSet resultado = co.consultar(SentenciaSQL);
            while (resultado.next()) {
                nombre = resultado.getString("Nombre");
                etiqueta = resultado.getInt("etiqueta");
                tipo = resultado.getString("tipo");
                precio = resultado.getFloat("precio");
                Nimagen = resultado.getString("Nimagen");
                stock1 = resultado.getInt("Stock");

                textoProducto1 = "<html>"
                        + "<center><b>&emsp;&emsp;Nombre:</b> " + nombre + "<br>"
                        + "<b>Categoría:</b>" + tipo + "<br>"
                        + "<b>&emsp;Precio:</b>" + precio + " pesos" + "<br>"
                        + "<b>&emsp;Unidades disponibles:</b> " + stock1 + "</center>"
                        + "</html>";

                String Ruta = "D:/prueba/" + Nimagen;
                Image mImage = new ImageIcon(Ruta).getImage();
                ImageIcon mIcono = new ImageIcon(mImage.getScaledInstance(promo.getWidth(), promo.getHeight(), Image.SCALE_SMOOTH));
                promo.setIcon(mIcono);
                Text.setText(textoProducto1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "BD", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            System.out.println("Error al cargar la imagen: " + e.getMessage());
        }
    }
    String nombre2;
    float precio2;
    String tipo2;
    String Nimagen2;
    int etiqueta2;
    String textoProducto2;
    int stock2;

    public void LabelM2(JLabel promo, int ID, JLabel Text) {
        String SentenciaSQL = "Select Nombre, etiqueta, tipo, precio, Nimagen, Stock FROM Productos WHERE etiqueta = " + ID;
        try {

            ResultSet resultado = co.consultar(SentenciaSQL);
            while (resultado.next()) {
                nombre2 = resultado.getString("Nombre");
                etiqueta2 = resultado.getInt("etiqueta");
                tipo2 = resultado.getString("tipo");
                precio2 = resultado.getFloat("precio");
                Nimagen2 = resultado.getString("Nimagen");
                stock2 = resultado.getInt("Stock");

                textoProducto2 = "<html>"
                        + "<center><b>&emsp;&emsp;Nombre:</b> " + nombre2 + "<br>"
                        + "<b>Categoría:</b>" + tipo2 + "<br>"
                        + "<b>&emsp;Precio:</b>" + precio2 + " pesos" + "<br>"
                        + "<b>&emsp;Unidades disponibles:</b> " + stock2 + "</center>"
                        + "</html>";

                String Ruta = "D:/prueba/" + Nimagen2;
                Image mImage = new ImageIcon(Ruta).getImage();
                ImageIcon mIcono = new ImageIcon(mImage.getScaledInstance(promo.getWidth(), promo.getHeight(), Image.SCALE_SMOOTH));
                promo.setIcon(mIcono);
                Text.setText(textoProducto2);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "BD", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            System.out.println("Error al cargar la imagen: " + e.getMessage());
        }
    }
    String nombre3;
    float precio3;
    String tipo3;
    String Nimagen3;
    int etiqueta3;
    int stock3;
    String textoProducto3;

    public void LabelM3(JLabel promo, int ID, JLabel Text) {
        String SentenciaSQL = "Select Nombre, etiqueta, tipo, precio, Nimagen, Stock FROM Productos WHERE etiqueta = " + ID;
        try {

            ResultSet resultado = co.consultar(SentenciaSQL);
            while (resultado.next()) {
                nombre3 = resultado.getString("Nombre");
                tipo3 = resultado.getString("tipo");
                etiqueta3 = resultado.getInt("etiqueta");
                precio3 = resultado.getFloat("precio");
                Nimagen3 = resultado.getString("Nimagen");
                stock3 = resultado.getInt("Stock");

                textoProducto3 = "<html>"
                        + "<center><b>&emsp;&emsp;Nombre:</b> " + nombre3 + "<br>"
                        + "<b>Categoría:</b>" + tipo3 + "<br>"
                        + "<b>&emsp;Precio:</b>" + precio3 + " pesos" + "<br>"
                        + "<b>&emsp;Unidades disponibles:</b> " + stock3 + "</center>"
                        + "</html>";

                String Ruta = "D:/prueba/" + Nimagen3;
                Image mImage = new ImageIcon(Ruta).getImage();
                ImageIcon mIcono = new ImageIcon(mImage.getScaledInstance(promo.getWidth(), promo.getHeight(), Image.SCALE_SMOOTH));
                promo.setIcon(mIcono);
                Text.setText(textoProducto3);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "BD", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            System.out.println("Error al cargar la imagen: " + e.getMessage());
        }
    }

    public void tra() {
        Configuracion configuracion = Configuracion.getInstance(); // Obtiene la instancia compartida
        boolean idiomaActual = configuracion.isIdioma();
        Home.setText(idiomaActual ? "Inicio" : "Home");
        Nombre.setText(idiomaActual ? "SECCION MASCULINA" : "Men's section");
        Bienvenido3.setText(idiomaActual ? "Categorias" : "Category");
        Mujer.setText(idiomaActual ? "Mujer" : "Woman");
        Hombre.setText(idiomaActual ? "Hombre" : "Man");
        Niño.setText(idiomaActual ? "Niño/a" : "Children");
        Accesorios.setText(idiomaActual ? "Accesorios" : "Accessories");
        Carrito.setText(idiomaActual ? "Carrito" : "Shopping");
        Bienvenido2.setText(idiomaActual ? "Acerca de:" : "About:");
        Filtrar.setText(idiomaActual ? "Filtrar" : "Filter");
        NoFil.setText(idiomaActual ? "Quitar filtros" : "Remove filters");
        addC1.setText(idiomaActual ? "Agregar al carrito" : "Add to cart");
        addC2.setText(idiomaActual ? "Agregar al carrito" : "Add to cart");
        addC3.setText(idiomaActual ? "Agregar al carrito" : "Add to cart");
        redes.setText(idiomaActual ? "Siguenos en nuestras redes" : "Follow us in our social medias");
        Contacto1.setText(idiomaActual ? "Contactanos" : "Contact us");
        

        String nameLabel = idiomaActual ? "Nombre:" : "Name:";
        String categoryLabel = idiomaActual ? "Categoría:" : "Category:";
        String prizeLabel = idiomaActual ? "Precio:" : "Price:";
        String stockLabel = idiomaActual ? "Unidades disponibles:" : "stock:";

        textoProducto1 = "<html>"
                + "<center><b>&emsp;&emsp;" + nameLabel + "</b> " + nombre + "<br>"
                + "<b>" + categoryLabel + "</b> " + tipo + "<br>"
                + "<b>&emsp;" + prizeLabel + "</b> " + precio + (idiomaActual ? " pesos" : " cop") + "<br>"
                + "<b>&emsp;" + stockLabel + "</b> " + stock1 + "</center>"
                + "</html>";

        textoProducto2 = "<html>"
                + "<center><b>&emsp;&emsp;" + nameLabel + "</b> " + nombre2 + "<br>"
                + "<b>" + categoryLabel + "</b> " + tipo2 + "<br>"
                + "<b>&emsp;" + prizeLabel + "</b> " + precio2 + (idiomaActual ? " pesos" : " cop") + "<br>"
                + "<b>&emsp;" + stockLabel + "</b> " + stock2 + "</center>"
                + "</html>";

        textoProducto3 = "<html>"
                + "<center><b>&emsp;&emsp;" + nameLabel + "</b> " + nombre3 + "<br>"
                + "<b>" + categoryLabel + "</b> " + tipo3 + "<br>"
                + "<b>&emsp;" + prizeLabel + "</b> " + precio3 + (idiomaActual ? " pesos" : " cop") + "<br>"
                + "<b>&emsp;" + stockLabel + "</b> " + stock3 + "</center>"
                + "</html>";

        Info1.setText(textoProducto1);
        Info2.setText(textoProducto2);
        Info3.setText(textoProducto3);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mujer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mujer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mujer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mujer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hombre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accesorios;
    private javax.swing.JLabel Bienvenido2;
    private javax.swing.JLabel Bienvenido3;
    private javax.swing.JPanel CMA;
    private javax.swing.JButton Carrito;
    private javax.swing.JTextField Contacto1;
    private javax.swing.JButton Filtrar;
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton Hombre;
    private javax.swing.JButton Home;
    private javax.swing.JLabel IconoBuscar;
    private javax.swing.JLabel Image1;
    private javax.swing.JLabel Image2;
    private javax.swing.JLabel Image3;
    private javax.swing.JLabel Info1;
    private javax.swing.JLabel Info2;
    private javax.swing.JLabel Info3;
    private javax.swing.JButton Instagram;
    private javax.swing.JButton Instagram1;
    private javax.swing.JPanel LDown;
    private javax.swing.JPanel Lup;
    private javax.swing.JButton Mcerrar;
    private javax.swing.JPanel Menu1;
    private javax.swing.JButton Mminimizar;
    private javax.swing.JButton Mujer;
    private javax.swing.JButton Niño;
    private javax.swing.JButton NoFil;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton Sig;
    private javax.swing.JButton Twitter;
    private javax.swing.JButton addC1;
    private javax.swing.JButton addC2;
    private javax.swing.JButton addC3;
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> filtro;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField redes;
    // End of variables declaration//GEN-END:variables
}
